<Project>
  <PropertyGroup>
    <VersionPrefix>0.1.0</VersionPrefix>
    <VersionSuffix>dev</VersionSuffix>
    <Authors>EPUB翻译 contributors</Authors>
    <Company>EPUB翻译</Company>
    <Product>EPUB翻译 Windows Edition</Product>
    <Copyright>Copyright © 2026 EPUB翻译 contributors</Copyright>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <Platforms>x64;ARM64</Platforms>
  </PropertyGroup>
</Project>
